#!/bin/bash
dir="/sys/class/power_supply/BAT0/"
status=$( cat $dir"status" )
capacity=$( cat $dir"charge_full_design" )
current=$( cat $dir"charge_now" )
percentage=$((current*100/capacity))
if [[ $status = "Discharging" && $percentage -le 20 ]];
then
  echo "#[fg=red] $percentage% (VERY LOW) #[fg=black]• #[fg=cyan]%I:%M #[default]"
elif [[ $status = "Discharging" && $percentage -ge 20 ]];
then
  echo "#[fg=white] $percentage% #[fg=black]• #[fg=cyan]%I:%M #[default]"
elif [[ $status = "Charging" ]];
then
  echo "#[fg=green] $percentage% #[fg=black]• #[fg=cyan]%I:%M #[default]"
else
  echo "#[fg=yellow] $percentage% #[fg=black]• #[fg=cyan]%I:%M #[default]"
fi
